#include "engine"

// DO NOT PUT ANYTHING IN INDEX 0 OR YOU WILL BREAK THINGS

//----------------------------------------------------------------------------//

// Area Types
const int AREA_LIBRARY_TYPE_CAVE    = 1;
const int AREA_LIBRARY_TYPE_CRYPT   = 2;
const int AREA_LIBRARY_TYPE_DUNGEON = 3;

// Creature Types
const int CREATURE_LIBRARY_TYPE_ANIMAL_RAT      =  1;
const int CREATURE_LIBRARY_TYPE_ANINAL_WOLF     =  2;
const int CREATURE_LIBRARY_TYPE_ANIMAL_BEAR     =  3;
const int CREATURE_LIBRARY_TYPE_ANIMAL_BADGER   =  4;
const int CREATURE_LIBRARY_TYPE_GOBLIN          =  5;
const int CREATURE_LIBRARY_TYPE_ORC             =  6;
const int CREATURE_LIBRARY_TYPE_GNOLL           =  7;
const int CREATURE_LIBRARY_TYPE_OGRE            =  8;
const int CREATURE_LIBRARY_TYPE_TROLL           =  9;
const int CREATURE_LIBRARY_TYPE_UNDEAD          = 10;
const int CREATURE_LIBRARY_TYPE_SHADOWS         = 11;
const int CREATURE_LIBRARY_TYPE_OWLBEAR         = 12;
const int CREATURE_LIBRARY_TYPE_WYVERN          = 13;
const int CREATURE_LIBRARY_TYPE_ETIN            = 14;
const int CREATURE_LIBRARY_TYPE_GIANT_HILL      = 15;
const int CREATURE_LIBRARY_TYPE_GIANT_STONE     = 16;
const int CREATURE_LIBRARY_TYPE_GIANT_FIRE      = 17;
const int CREATURE_LIBRARY_TYPE_GIANT_FROST     = 18;
const int CREATURE_LIBRARY_TYPE_BUGBEAR         = 19;

// Creature Regions (amalgamations of several different creature types)
const int CREATURE_LIBRARY_REGION_CORMYR_HULLACK     = 1;
const int CREATURE_LIBRARY_REGION_CORMYR_KINGSFOREST = 2;
const int CREATURE_LIBRARY_REGION_CORMYR_STONELANDS  = 3;
const int CREATURE_LIBRARY_REGION_CORMYR_STORMHORNS  = 4;
const int CREATURE_LIBRARY_REGION_CORMYR_ARABELENV   = 5;
const int CREATURE_LIBRARY_REGION_CORMYR_TILVERTON   = 6;

// Number of creature types per region
const int CREATURE_LIBRARY_SUBTYPES_CORMYR_HULLACK     = 1;
const int CREATURE_LIBRARY_SUBTYPES_CORMYR_KINGSFOREST = 2;
const int CREATURE_LIBRARY_SUBTYPES_CORMYR_STONELANDS  = 3;
const int CREATURE_LIBRARY_SUBTYPES_CORMYR_STORMHORNS  = 4;
const int CREATURE_LIBRARY_SUBTYPES_CORMYR_ARABELENV   = 5;
const int CREATURE_LIBRARY_SUBTYPES_CORMYR_TILVERTON   = 6;

// Weight of occurence of various creature types by region
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_RAT=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_WOLF=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BEAR=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BADGER=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GOBLIN=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ORC=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GNOLL=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_TROLL=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_OWLBEAR=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_WYVERN=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ETIN=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_BUGBEAR=1;

const int CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_RAT=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_WOLF=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BEAR=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BADGER=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_OWLBEAR=1;

const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_RAT=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_WOLF=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BEAR=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BADGER=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GOBLIN=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ORC=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GNOLL=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_WYVERN=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ETIN=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_BUGBEAR=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_OGRE=1;
const int CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GIANT_HILL=1;

const int CREATURE_LIBRARY_WEIGHT_CORMYR_STORMHORNS=1;

const int CREATURE_LIBRARY_WEIGHT_CORMYR_ARABELENV=1;

const int CREATURE_LIBRARY_WEIGHT_CORMYR_TILVERTON=1;

//----------------------------------------------------------------------------//

const string AREA_LIBRARY_ARRAY_CAVE    = "||inst_ar_cv_0|inst_ar_cv_1|inst_ar_cv_2|inst_ar_cv_3|inst_ar_cv_4|inst_ar_cv_5|inst_ar_cv_6|inst_ar_cv_7|inst_ar_cv_8|inst_ar_cv_9";
const string AREA_LIBRARY_ARRAY_CRYPT   = "||";
const string AREA_LIBRARY_ARRAY_DUNGEON = "||";

const string AREA_LIBRARY_ARRAY_CAP_CAVE    = "||inst_cp_cv_01|inst_cp_cv_02|inst_cp_cv_03|inst_cp_cv_04|inst_cp_cv_05|inst_cp_cv_06|inst_cp_cv_07|inst_cp_cv_08|inst_cp_cv_09|inst_cp_cv_10";
const string AREA_LIBRARY_ARRAY_CAP_CRYPT   = "||";
const string AREA_LIBRARY_ARRAY_CAP_DUNGEON = "||";

const string AREA_LIBRARY_ARRAY_ENT_CAVE = "||inst_ent_cv_0|inst_ent_cv_1|inst_ent_cv_2|inst_ent_cv_3";
const string AREA_LIBRARY_ARRAY_ENT_CRYPT = "||";
const string AREA_LIBRARY_ARRAY_ENT_DUNGEON = "||";

const string CREATURE_LIBRARY_ARRAY_ANIMAL_RAT     = "||";
const string CREATURE_LIBRARY_ARRAY_ANIMAL_WOLF    = "||";
const string CREATURE_LIBRARY_ARRAY_ANIMAL_BEAR    = "||";
const string CREATURE_LIBRARY_ARRAY_ANIMAL_BADGER  = "||";
const string CREATURE_LIBRARY_ARRAY_GOBLIN         = "||";
const string CREATURE_LIBRARY_ARRAY_ORC            = "||";
const string CREATURE_LIBRARY_ARRAY_GNOLL          = "||";
const string CREATURE_LIBRARY_ARRAY_OGRE           = "||";
const string CREATURE_LIBRARY_ARRAY_TROLL          = "||";
const string CREATURE_LIBRARY_ARRAY_UNDEAD         = "||";
const string CREATURE_LIBRARY_ARRAY_SHADOWS        = "||";
const string CREATURE_LIBRARY_ARRAY_OWLBEAR        = "||";
const string CREATURE_LIBRARY_ARRAY_WYVERN         = "||";
const string CREATURE_LIBRARY_ARRAY_ETIN           = "||";
const string CREATURE_LIBRARY_ARRAY_GIANT_HILL     = "||";
const string CREATURE_LIBRARY_ARRAY_GIANT_STONE    = "||";
const string CREATURE_LIBRARY_ARRAY_GIANT_FIRE     = "||";
const string CREATURE_LIBRARY_ARRAY_GIANT_FROST    = "||";
const string CREATURE_LIBRARY_ARRAY_BUGBEAR        = "||";

const string CREATURE_LIBRARY_ARRAY_STONELANDS_ORC = "||tsl_re_orc_000|tsl_re_orc_001|tsl_re_orc_002|tsl_re_orc_003";

//----------------------------------------------------------------------------//

// Returns standard area parts (linear portions with an entrance and exit).
string GetStandardAreaLibrary(int nAreaType);

// Returns capped area parts (portions with only an entrance).
string GetCappedAreaLibrary(int nAreaType);

// Returns a creature library array corresponding to a type of creature.
string GetCreatureLibrary(int nCreatureType);

// Returns a creature library array by randomly selecting from several
// available per region.
string GetCreatureLibraryByRegion(int nRegion);

//----------------------------------------------------------------------------//

string GetStandardAreaLibrary(int nAreaType) {
    switch(nAreaType) {
        case AREA_LIBRARY_TYPE_CAVE:    return AREA_LIBRARY_ARRAY_CAVE;    break;
        case AREA_LIBRARY_TYPE_CRYPT:   return AREA_LIBRARY_ARRAY_CRYPT;   break;
        case AREA_LIBRARY_TYPE_DUNGEON: return AREA_LIBRARY_ARRAY_DUNGEON; break;
    }

    return "";
}

string GetCappedAreaLibrary(int nAreaType) {
    switch(nAreaType) {
        case AREA_LIBRARY_TYPE_CAVE:    return AREA_LIBRARY_ARRAY_CAP_CAVE;    break;
        case AREA_LIBRARY_TYPE_CRYPT:   return AREA_LIBRARY_ARRAY_CAP_CRYPT;   break;
        case AREA_LIBRARY_TYPE_DUNGEON: return AREA_LIBRARY_ARRAY_CAP_DUNGEON; break;
    }

    return "";
}

string GetCreatureLibrary(int nCreatureType) {
    switch(nCreatureType) {
        case CREATURE_LIBRARY_TYPE_ANIMAL_RAT:     return CREATURE_LIBRARY_ARRAY_ANIMAL_RAT;     break;
        case CREATURE_LIBRARY_TYPE_ANINAL_WOLF:    return CREATURE_LIBRARY_ARRAY_ANIMAL_WOLF;    break;
        case CREATURE_LIBRARY_TYPE_ANIMAL_BEAR:    return CREATURE_LIBRARY_ARRAY_ANIMAL_BEAR;    break;
        case CREATURE_LIBRARY_TYPE_ANIMAL_BADGER:  return CREATURE_LIBRARY_ARRAY_ANIMAL_BADGER;  break;
        case CREATURE_LIBRARY_TYPE_GOBLIN:         return CREATURE_LIBRARY_ARRAY_GOBLIN;         break;
        case CREATURE_LIBRARY_TYPE_ORC:            return CREATURE_LIBRARY_ARRAY_ORC;            break;
        case CREATURE_LIBRARY_TYPE_GNOLL:          return CREATURE_LIBRARY_ARRAY_GNOLL;          break;
        case CREATURE_LIBRARY_TYPE_OGRE:           return CREATURE_LIBRARY_ARRAY_OGRE;           break;
        case CREATURE_LIBRARY_TYPE_TROLL:          return CREATURE_LIBRARY_ARRAY_TROLL;          break;
        case CREATURE_LIBRARY_TYPE_UNDEAD:         return CREATURE_LIBRARY_ARRAY_UNDEAD;         break;
        case CREATURE_LIBRARY_TYPE_SHADOWS:        return CREATURE_LIBRARY_ARRAY_SHADOWS;        break;
        case CREATURE_LIBRARY_TYPE_OWLBEAR:        return CREATURE_LIBRARY_ARRAY_OWLBEAR;        break;
        case CREATURE_LIBRARY_TYPE_WYVERN:         return CREATURE_LIBRARY_ARRAY_WYVERN;         break;
        case CREATURE_LIBRARY_TYPE_ETIN:           return CREATURE_LIBRARY_ARRAY_ETIN;           break;
        case CREATURE_LIBRARY_TYPE_GIANT_HILL:     return CREATURE_LIBRARY_ARRAY_GIANT_HILL;     break;
        case CREATURE_LIBRARY_TYPE_GIANT_STONE:    return CREATURE_LIBRARY_ARRAY_GIANT_STONE;    break;
        case CREATURE_LIBRARY_TYPE_GIANT_FIRE:     return CREATURE_LIBRARY_ARRAY_GIANT_FIRE;     break;
        case CREATURE_LIBRARY_TYPE_GIANT_FROST:    return CREATURE_LIBRARY_ARRAY_GIANT_FROST;    break;
    }

    return "";
}

string GetCreatureLibraryByRegion(int nRegion) {
    int nRand;
    int nTotal;

    switch(nRegion) {
        case CREATURE_LIBRARY_REGION_CORMYR_HULLACK:
            nTotal = CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_RAT +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_WOLF +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BEAR +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BADGER +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GOBLIN +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ORC +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GNOLL +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_TROLL +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_OWLBEAR +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_WYVERN +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ETIN +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_BUGBEAR;

            nRand = Random(nTotal);

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_RAT) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_RAT);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_RAT;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_WOLF) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANINAL_WOLF);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_WOLF;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_BEAR);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BEAR;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BADGER) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_BADGER);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ANIMAL_BADGER;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GOBLIN) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_GOBLIN);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GOBLIN;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ORC) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ORC);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ORC;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GNOLL) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_GNOLL);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_GNOLL;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_TROLL) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_TROLL);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_TROLL;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_OWLBEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_OWLBEAR);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_OWLBEAR;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_WYVERN) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_WYVERN);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_WYVERN;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ETIN) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ETIN);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_ETIN;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_BUGBEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_BUGBEAR);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_HULLACK_BUGBEAR;

            break;
        case CREATURE_LIBRARY_REGION_CORMYR_KINGSFOREST:
            nTotal = CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_RAT +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_WOLF +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BEAR +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BADGER +
                     CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_OWLBEAR;

            nRand = Random(nTotal);

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_RAT) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_RAT);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_RAT;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_WOLF) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANINAL_WOLF);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_WOLF;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_BEAR);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BEAR;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BADGER) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_BADGER);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_ANIMAL_BADGER;

            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_OWLBEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_OWLBEAR);
            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_KINGSFOREST_OWLBEAR;

            break;
       // case CREATURE_LIBRARY_REGION_CORMYR_STONELANDS:
         //   nTotal = CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_RAT +
//                     CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_WOLF +
  //                   CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BEAR +
    //                 CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BADGER +
      //               CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GOBLIN +
        //             CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ORC +
          //           CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GNOLL +
            //         CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_WYVERN +
              //       CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ETIN +
                //     CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_BUGBEAR +
                  //   CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_OGRE +
                    // CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GIANT_HILL;

//            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_RAT) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_RAT);
  //          nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_RAT;

    //        if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_WOLF) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_WOLF);
      //      nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_WOLF;

        //    if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_BEAR);
          //  nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BEAR;

            //if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BADGER) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ANIMAL_BADGER);
//            nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ANIMAL_BADGER;

//            if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GOBLIN) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_GOBLIN);
  //          nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GOBLIN;

    //        if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ORC) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ORC);
      //      nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ORC;

        //    if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GNOLL) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_GNOLL);
          //  nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GNOLL;

            //if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_WYVERN) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_WYVERN);
            //nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_WYVERN;

           // if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ETIN) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_ETIN);
            //nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_ETIN;

          //  if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_BUGBEAR) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_BUGBEAR);
         //   nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_BUGBEAR;

        //    if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_OGRE) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_OGRE);
        //    nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_OGRE;

         //   if(nRand < CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GIANT_HILL) return GetCreatureLibrary(CREATURE_LIBRARY_TYPE_GIANT_HILL);
         //   nRand -= CREATURE_LIBRARY_WEIGHT_CORMYR_STONELANDS_GIANT_HILL;

       //     break;
       // case CREATURE_LIBRARY_REGION_CORMYR_STORMHORNS:
       //     break;
       // case CREATURE_LIBRARY_REGION_CORMYR_ARABELENV:
       //     break;
    }

    return "";
}
